import { Client, Policy, Claim, PolicyStatus, ClaimStatus, InsuranceClass } from '@shared/types';
import { subDays, addDays, format } from 'date-fns';
const today = new Date();
export const MOCK_CLIENTS: Client[] = [
  { id: 'cli-001', name: 'Innovate Corp', email: 'contact@innovate.com', phone: '555-0101', address: '123 Tech Park, Silicon Valley, CA', joinDate: format(subDays(today, 150), 'yyyy-MM-dd') },
  { id: 'cli-002', name: 'Quantum Solutions', email: 'info@quantum.io', phone: '555-0102', address: '456 Future Drive, Austin, TX', joinDate: format(subDays(today, 90), 'yyyy-MM-dd') },
  { id: 'cli-003', name: 'Apex Logistics', email: 'support@apexlog.com', phone: '555-0103', address: '789 Cargo Way, Chicago, IL', joinDate: format(subDays(today, 365), 'yyyy-MM-dd') },
  { id: 'cli-004', name: 'Starlight Hotels', email: 'reservations@starlight.com', phone: '555-0104', address: '101 Resort Blvd, Miami, FL', joinDate: format(subDays(today, 200), 'yyyy-MM-dd') },
  { id: 'cli-005', name: 'BuildRight Construction', email: 'projects@buildright.co', phone: '555-0105', address: '202 Builder Ave, Denver, CO', joinDate: format(subDays(today, 45), 'yyyy-MM-dd') },
];
export const MOCK_POLICIES: Policy[] = [
  { id: 'pol-001', policyNumber: 'MOT-2024-001', clientName: 'Innovate Corp', clientId: 'cli-001', insuranceClass: InsuranceClass.Motor, premium: 1200.00, startDate: format(subDays(today, 30), 'yyyy-MM-dd'), endDate: format(addDays(today, 335), 'yyyy-MM-dd'), status: PolicyStatus.Active, details: { vehicle: 'Tesla Model S', registration: 'INVCORP1' } },
  { id: 'pol-002', policyNumber: 'FIR-2024-002', clientName: 'Quantum Solutions', clientId: 'cli-002', insuranceClass: InsuranceClass.Fire, premium: 5000.00, startDate: format(subDays(today, 60), 'yyyy-MM-dd'), endDate: format(addDays(today, 305), 'yyyy-MM-dd'), status: PolicyStatus.Active, details: { property: 'Office Building at 456 Future Drive' } },
  { id: 'pol-003', policyNumber: 'MAR-2024-003', clientName: 'Apex Logistics', clientId: 'cli-003', insuranceClass: InsuranceClass.MarineCargo, premium: 2500.00, startDate: format(subDays(today, 10), 'yyyy-MM-dd'), endDate: format(addDays(today, 80), 'yyyy-MM-dd'), status: PolicyStatus.Pending, details: { cargo: 'Electronics from Shanghai to LA' } },
  { id: 'pol-004', policyNumber: 'EMP-2023-004', clientName: 'Starlight Hotels', clientId: 'cli-004', insuranceClass: InsuranceClass.EmployeeCompensation, premium: 15000.00, startDate: format(subDays(today, 200), 'yyyy-MM-dd'), endDate: format(addDays(today, 165), 'yyyy-MM-dd'), status: PolicyStatus.Active, details: { employees: 150 } },
  { id: 'pol-005', policyNumber: 'MED-2023-005', clientName: 'Innovate Corp', clientId: 'cli-001', insuranceClass: InsuranceClass.Medical, premium: 8000.00, startDate: format(subDays(today, 100), 'yyyy-MM-dd'), endDate: format(addDays(today, 265), 'yyyy-MM-dd'), status: PolicyStatus.Active, details: { plan: 'Group Health Plan - Gold' } },
  { id: 'pol-006', policyNumber: 'TRV-2024-006', clientName: 'Quantum Solutions', clientId: 'cli-002', insuranceClass: InsuranceClass.Travel, premium: 500.00, startDate: format(subDays(today, 5), 'yyyy-MM-dd'), endDate: format(addDays(today, 25), 'yyyy-MM-dd'), status: PolicyStatus.Active, details: { destination: 'Europe' } },
  { id: 'pol-007', policyNumber: 'MOT-2023-007', clientName: 'Apex Logistics', clientId: 'cli-003', insuranceClass: InsuranceClass.Motor, premium: 3200.00, startDate: format(subDays(today, 400), 'yyyy-MM-dd'), endDate: format(subDays(today, 35), 'yyyy-MM-dd'), status: PolicyStatus.Expired, details: { vehicle: 'Ford Transit Fleet', registration: 'APXFLT1' } },
  { id: 'pol-008', policyNumber: 'FIR-2023-008', clientName: 'BuildRight Construction', clientId: 'cli-005', insuranceClass: InsuranceClass.Fire, premium: 7500.00, startDate: format(subDays(today, 180), 'yyyy-MM-dd'), endDate: format(addDays(today, 185), 'yyyy-MM-dd'), status: PolicyStatus.Cancelled, details: { property: 'Construction Site A' } },
];
export const MOCK_CLAIMS: Claim[] = [
  { id: 'clm-001', claimNumber: 'CLM-MOT-001', policyNumber: 'MOT-2024-001', policyId: 'pol-001', clientName: 'Innovate Corp', clientId: 'cli-001', claimDate: format(subDays(today, 5), 'yyyy-MM-dd'), amount: 2500.00, status: ClaimStatus.Open, description: 'Minor collision, front bumper damage.' },
  { id: 'clm-002', claimNumber: 'CLM-EMP-002', policyNumber: 'EMP-2023-004', policyId: 'pol-004', clientName: 'Starlight Hotels', clientId: 'cli-004', claimDate: format(subDays(today, 45), 'yyyy-MM-dd'), amount: 1200.00, status: ClaimStatus.Approved, description: 'Workplace injury, slip and fall.' },
  { id: 'clm-003', claimNumber: 'CLM-FIR-003', policyNumber: 'FIR-2024-002', policyId: 'pol-002', clientName: 'Quantum Solutions', clientId: 'cli-002', claimDate: format(subDays(today, 20), 'yyyy-MM-dd'), amount: 15000.00, status: ClaimStatus.Open, description: 'Water damage from sprinkler system malfunction.' },
  { id: 'clm-004', claimNumber: 'CLM-MED-004', policyNumber: 'MED-2023-005', policyId: 'pol-005', clientName: 'Innovate Corp', clientId: 'cli-001', claimDate: format(subDays(today, 60), 'yyyy-MM-dd'), amount: 850.00, status: ClaimStatus.Closed, description: 'Routine medical check-up and prescription.' },
  { id: 'clm-005', claimNumber: 'CLM-MOT-005', policyNumber: 'MOT-2023-007', policyId: 'pol-007', clientName: 'Apex Logistics', clientId: 'cli-003', claimDate: format(subDays(today, 90), 'yyyy-MM-dd'), amount: 500.00, status: ClaimStatus.Rejected, description: 'Claim filed after policy expiration.' },
];